[package]
name = "myacccounts"
version = "0.1.0"
authors = ["DavidS <david@tan.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
chrono = "0.4"
rust_decimal = "1.8.1"
